import 'dotenv/config';import bcrypt from 'bcryptjs';import {PrismaClient} from '@prisma/client';import {PrismaPg} from '@prisma/adapter-pg';
const adapter=new PrismaPg({connectionString:process.env.DATABASE_URL});
const prisma=new PrismaClient({adapter});
const products=[
 {slug:'mango',name:'Mango',category:'Fruits',shortDescription:'Sun-ripened mango, gently preserved.',description:'Selected mango with a naturally intense fruit character. Made for snacking, breakfast bowls and slow moments.',price:349,compareAtPrice:399,stock:80,sku:'TAZA-MNG-100',weightGrams:100,ingredients:'Mango'},
 {slug:'pineapple',name:'Pineapple',category:'Fruits',shortDescription:'Bright, tangy pineapple with a clean finish.',description:'A tropical favourite, carefully sliced and preserved to keep its distinctive aroma and tangy sweetness.',price:329,stock:70,sku:'TAZA-PIN-100',weightGrams:100,ingredients:'Pineapple'},
 {slug:'guava',name:'Guava',category:'Fruits',shortDescription:'Fragrant guava with a soft tropical sweetness.',description:'A fragrant fruit with a distinct Bangladeshi character, preserved with care for an easy everyday snack.',price:319,stock:60,sku:'TAZA-GUA-100',weightGrams:100,ingredients:'Guava'},
 {slug:'citrus-infusion',name:'Citrus Infusion',category:'Infusions',shortDescription:'Citrus slices for tea, water and slow infusions.',description:'Bright citrus slices designed for cups, pitchers and creative infusions. A beautiful pantry staple.',price:399,stock:50,sku:'TAZA-CIT-60',weightGrams:60,ingredients:'Citrus'},
 {slug:'hibiscus',name:'Hibiscus',category:'Botanicals',shortDescription:'Deep floral hibiscus for vibrant infusions.',description:'A naturally vivid botanical for tea, cold infusions and quiet evening rituals.',price:299,stock:45,sku:'TAZA-HIB-50',weightGrams:50,ingredients:'Hibiscus'},
 {slug:'spearmint',name:'Spearmint',category:'Botanicals',shortDescription:'Cool, aromatic mint for everyday infusions.',description:'Freshly aromatic spearmint leaves, carefully dried for a clean and refreshing cup.',price:279,stock:55,sku:'TAZA-SPM-30',weightGrams:30,ingredients:'Spearmint'}
];
async function main(){const hash=await bcrypt.hash('ChangeMe123!',12);await prisma.user.upsert({where:{email:'admin@taza.bd'},update:{},create:{name:'TAZA Admin',email:'admin@taza.bd',passwordHash:hash,role:'ADMIN'}});for(const p of products)await prisma.product.upsert({where:{slug:p.slug},update:p,create:p});console.log('Seed complete. Admin: admin@taza.bd / ChangeMe123!');}main().finally(()=>prisma.$disconnect());
