import {Router} from 'express';import {z} from 'zod';import {prisma} from '../db';import {requireAuth,requireRole,optionalAuth} from '../middleware/auth';import {Role} from '../generated/prisma/client';import {calculateCoupon,createOrderNumber} from '../services';
const r=Router();
const orderSchema=z.object({customerName:z.string().min(2),email:z.string().email(),phone:z.string().min(6),address:z.string().min(5),city:z.string().default('Dhaka'),postalCode:z.string().optional(),paymentMethod:z.enum(['COD','BKASH','NAGAD','SSL_COMMERZ']).default('COD'),couponCode:z.string().optional(),partnerCode:z.string().optional(),items:z.array(z.object({productId:z.string(),quantity:z.number().int().positive().max(50)})).min(1).max(50)});
r.post('/',optionalAuth,async(req,res,next)=>{try{const d=orderSchema.parse(req.body);const ids=[...new Set(d.items.map(i=>i.productId))];const products=await prisma.product.findMany({where:{id:{in:ids},active:true}});if(products.length!==ids.length)return res.status(400).json({message:'One or more products are unavailable'});const map=new Map(products.map(p=>[p.id,p]));let subtotal=0;for(const i of d.items){const p=map.get(i.productId)!;if(p.stock<i.quantity)return res.status(400).json({message:`Insufficient stock for ${p.name}`});subtotal+=p.price*i.quantity;}
let discount=0;let couponId:string|undefined;if(d.couponCode){const c=await prisma.coupon.findUnique({where:{code:d.couponCode.toUpperCase()}});const now=new Date();if(!c||!c.active||(c.startsAt&&c.startsAt>now)||(c.expiresAt&&c.expiresAt<now)||(c.maxUses!==null&&c.usedCount>=c.maxUses)||subtotal<c.minOrder)return res.status(400).json({message:'Coupon is not valid for this order'});discount=calculateCoupon(c.type,c.value,subtotal);couponId=c.id;}
const deliveryFee=Math.max(0,subtotal-discount)>=3000?0:80;const total=subtotal+deliveryFee-discount;let partnerId:string|undefined;if(d.partnerCode){partnerId=(await prisma.partner.findUnique({where:{code:d.partnerCode}}))?.id;}
const userId=req.auth?.userId;const order=await prisma.$transaction(async tx=>{const o=await tx.order.create({data:{orderNumber:createOrderNumber(),userId,partnerId,customerName:d.customerName,email:d.email.toLowerCase(),phone:d.phone,address:d.address,city:d.city,postalCode:d.postalCode,subtotal,deliveryFee,discount,total,paymentMethod:d.paymentMethod,couponCode:d.couponCode?.toUpperCase(),items:{create:d.items.map(i=>({productId:i.productId,productName:map.get(i.productId)!.name,quantity:i.quantity,unitPrice:map.get(i.productId)!.price}))}}});for(const i of d.items){const result=await tx.product.updateMany({where:{id:i.productId,stock:{gte:i.quantity}},data:{stock:{decrement:i.quantity}}});if(result.count!==1)throw new Error('Stock changed; please retry');}if(couponId)await tx.coupon.update({where:{id:couponId},data:{usedCount:{increment:1}}});if(partnerId){const partner=await tx.partner.findUnique({where:{id:partnerId}});if(partner)await tx.partnerCommission.create({data:{partnerId,orderId:o.id,amount:Math.floor(total*partner.commissionRate/100)}});}return o;});res.status(201).json({order:{id:order.id,orderNumber:order.orderNumber,total:order.total,status:order.status,paymentStatus:order.paymentStatus}})}catch(e){next(e)}});
r.get('/mine',requireAuth,async(req,res,next)=>{try{res.json({orders:await prisma.order.findMany({where:{userId:req.auth!.userId},include:{items:true},orderBy:{createdAt:'desc'}})})}catch(e){next(e)}});
r.get('/:id',optionalAuth,async(req,res,next)=>{try{const o=await prisma.order.findUnique({where:{id:req.params.id},include:{items:true}});if(!o)return res.status(404).json({message:'Order not found'});if(req.auth?.role!==Role.ADMIN&&o.userId!==req.auth?.userId)return res.status(403).json({message:'Forbidden'});res.json({order:o})}catch(e){next(e)}});
r.get('/',requireAuth,requireRole(Role.ADMIN),async(req,res,next)=>{try{const status=String(req.query.status||'');res.json({orders:await prisma.order.findMany({where:status?{status:status as any}:undefined,include:{items:true,commission:true},orderBy:{createdAt:'desc'},take:200})})}catch(e){next(e)}});
r.patch('/:id/status',requireAuth,requireRole(Role.ADMIN),async(req,res,next)=>{try{const d=z.object({status:z.enum(['PENDING','CONFIRMED','PROCESSING','SHIPPED','DELIVERED','CANCELLED','REFUNDED'])}).parse(req.body);const order=await prisma.order.update({where:{id:req.params.id},data:{status:d.status}});res.json({order})}catch(e){next(e)}});
export default r;
